version: '3.9'

# Services
services:

  # Nginx Service
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 80:80
    volumes:
      - ./src/backend:/var/www/backend
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend

  # Backend Service
  backend:
    build: ./src/backend
    user: ${UID}:${UID}
    working_dir: /var/www/backend
    volumes:
      - ./src/backend:/var/www/backend
    depends_on:
      mysql:
        condition: service_healthy

  # Frontend Service
  frontend:
    build: ./src/frontend
    user: ${UID}:${UID}
    working_dir: /var/www/frontend
    volumes:
      - ./src/frontend:/var/www/frontend
    ports:
      - '3000:3000' # For docker to now where to redirect HMR queries
    depends_on:
      - backend

  # MySQL Service
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: DB_ROOT_PASSWORD
      MYSQL_DATABASE: DB_DATABASE
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

# Volumes
volumes:

  mysqldata:
